NearNodeFlash/nnf-ec

.github/workflows/main.yml, CONTRIBUTING.md, Dockerfile
These changes trigger a docker build which runs the tests in github actions. Thanks to @billhpe for the heavy lifting.
=> Modify dockerfile and add github actions to build the dockerfile.

tools/bind.sh, tools/debug.sh, tools/ns.sh, tools/rabbit-s.sh
=> Rabbit management and debug tools

tools/rabbit-s.sh
=> Fix for enable-logging not working; Fix for lnkstat output wrapping

tools/rabbit-s.sh
=> Additional rabbit-s commands; polish

tools/create-write-delete-namespaces.sh, tools/nvme.sh, tools/rabbit-s.sh
Timing info added to NVME commands, as well as the script to create/write/delete namespaces.
=> Improvements to tool scripts to troubleshoot MC issues

tools/nvme.sh
=> Remove redundancy in nvme.sh script. New command to run any nvme command

pkg/manager-nvme/manager.go
=> Only log Attach/Detach errors

.vscode/launch.json, pkg/rfsf/pkg/common/oem.go, pkg/rfsf/pkg/common/oem_test.go
=> Slice marshal/unmarshal

tools/nvme.sh
=> Add list-pfid option to nvme.sh along with more examples

tools/nvme.sh
=> Tune-up help for nvme.sh

pkg/manager-nnf/storage_pool.go, pkg/manager-nvme/manager.go
Was clearly not thinking with my last fix and was duplicating storage pools.
For debug I threw in some simple logging to track storage pool recovery and nvme initialization; figured I might as well leave it in.
There's an open TODO that I highlighted if we crash while the storage pool is being created. I might task this to Blake as he's looking for stuff to do.
=> Resolution for Storage Pool not recovering after restart

scripts/hpecray-17.py
=> Python script to try and reproduce HPECRAY-17

pkg/manager-nnf/manager.go
=> NNF Manager initialize resource health

pkg/manager-nnf/manager.go
=> Storage service should not go enabled until after recovery has completed

tools/switch.sh
=> slot and status displays for switches

internal/switchtec/cmd/fabric/csr.go, internal/switchtec/cmd/fabric/vf-reset.go, internal/switchtec/main.go, internal/switchtec/pkg/switchtec/csr.go, internal/switchtec/pkg/switchtec/pci.go, pkg/manager-fabric/manager.go, pkg/manager-fabric/switchtec_api.go, pkg/manager-fabric/switchtec_cli.go, pkg/manager-fabric/switchtec_device.go, pkg/manager-fabric/switchtec_mock.go, pkg/manager-nvme/manager.go
Perform a Function Level Reset (FLR) after assigning VI/VQ resources to the Virtual Function (VF)
=> VF Reset Support

tools/rabbit-s.sh
Tidy up the switchtec logging used to troubleshoot PAX issues.
=> Switchtec logging cleanup

pkg/manager-nvme/manager.go
The AttachDetach block surrounds all format commands. If the physical function controller ID is attached and detached, we reduce noise in the Rabbit/Compute node space.
Background
If you look at https://github.com/NearNodeFlash/nnf-ec/pull/76, you can see that I did not deal with the physical function correctly which causes old KIOXIA CD7 drives to fail to attach to the correct controller ID. This change restores that special case while preserving the proper operation of the virt-mgmt drives
=> Use the physical function ID as the attach ID for AttachDetach block

scripts/admin-node-scripts/Rabbit_FWnCabling_tests/BlastImages.sh, scripts/admin-node-scripts/Rabbit_FWnCabling_tests/FWnCablingTest.sh, scripts/admin-node-scripts/Rabbit_FWnCabling_tests/PAX_logs.sh, scripts/admin-node-scripts/Rabbit_FWnCabling_tests/Prgrm_nc.sh, scripts/admin-node-scripts/Rabbit_FWnCabling_tests/Rabbit_Assy_Prod_Test_v1-1.sh, scripts/admin-node-scripts/Rabbit_FWnCabling_tests/reboot_nCs.sh, scripts/admin-node-scripts/Rabbit_FWnCabling_tests/updateDriveFirmware.sh, scripts/admin-node-scripts/simplePowerTest.sh
Add Tim McCree's manufacturing scripts
=> Add firmware programming and cabling tests for used in manufacturing

scripts/hpecray-17.py, tools/switch.sh
The display was chopping off part of the device column which turns out to be very useful.
=> Format fix for tools/switch.sh

tools/rabbit-s.sh
Add an additional set of logging to the rabbit-s configuration script.
=> Add addition PCIE logging to the Rabbit-s configuration script

Makefile
Closes https://github.com/NearNodeFlash/NearNodeFlash.github.io/issues/121
=> Set CGO_ENABLED=0 when building the command

Dockerfile, pkg/controller.go, pkg/ec/ec.go, pkg/manager-nnf/allocation_policy.go, pkg/manager-nnf/manager.go, pkg/manager-nnf/storage_pool.go, pkg/manager-nvme/manager.go, pkg/tests/benchmarks/benchmark_test.go, pkg/tests/filesystem/file_system_test.go, pkg/tests/nnf_test.go, pkg/tests/recovery/recovery_test.go
=> Release v0.1.2

pkg/manager-nnf/manager.go, pkg/manager-nvme/manager.go
=> Release v0.1.3

tools/nnf-nvme.sh, tools/nnf-rabbit-s.sh, tools/nnf-switch.sh
- Improve error handling for switch and nvme scripts
- Rename scripts to match convention onsite
=> Improve error handling for switch and nvme scripts

Readme.md, pkg/manager-nnf/allocation_policy.go, pkg/manager-nnf/manager.go, pkg/manager-nvme/manager.go, scripts/interactive.py, tools/nnf-nvme.sh, tools/nnf-rabbit-s.sh, tools/nnf-switch.sh
=> Release v0.1.5

tools/stat.sh
=> Add status scripts used to survey rabbit system status

pkg/manager-message-registry/registries/Nnf.1.0.0.go, pkg/manager-message-registry/registries/Nnf.1.0.0.json, pkg/manager-nnf/manager.go, pkg/manager-nnf/storage_pool.go, pkg/manager-nvme/manager.go, tools/lvm.sh, tools/zpool.sh
Emit a Storage Pool Patched event when a missing namespace is replaced with a new namespace.
=> Nnf ec missing volume

pkg/manager-message-registry/registries/Nnf.1.0.0.go, pkg/manager-message-registry/registries/Nnf.1.0.0.json, pkg/manager-nnf/manager.go, pkg/manager-nnf/storage_pool.go, pkg/manager-nvme/manager.go, tools/lvm.sh, tools/zpool.sh
=> Release v0.1.8

internal/switchtec/cmd/fabric/perf.go, internal/switchtec/pkg/nvme/nvme.go, pkg/manager-fabric/manager.go, pkg/manager-fabric/monitor.go, pkg/manager-message-registry/registries/Nnf.1.0.0.go, pkg/manager-message-registry/registries/Nnf.1.0.0.json, pkg/manager-nnf/allocation_policy.go, pkg/manager-nnf/manager.go, pkg/manager-nnf/storage_pool.go, pkg/manager-nvme/manager.go, pkg/manager-nvme/monitor.go, pkg/manager-nvme/nvme_api.go, pkg/manager-nvme/nvme_cli.go, pkg/manager-nvme/nvme_device.go, pkg/manager-nvme/nvme_direct_device.go, pkg/manager-nvme/nvme_mock.go
=> Release v0.1.10
