- pkg/manager-server/file_system_lustre.go
Use all of the provided devices when creating zpools for lustre targets.
Signed-off-by: Dean Roehrich <dean.roehrich@hpe.com>
> RABSW-933 nnf-ec: use all devices when creating zpools.

- pkg/manager-nnf/file_share.go
- pkg/manager-nnf/file_system.go
- pkg/manager-nnf/manager.go
- pkg/manager-server/file_system_api.go
- pkg/manager-server/file_system_gfs2.go
- pkg/manager-server/file_system_lustre.go
- pkg/manager-server/file_system_lvm.go
- pkg/manager-server/file_system_xfs.go
- pkg/manager-server/file_system_zfs.go
- pkg/manager-server/server_api.go
- pkg/manager-server/server_disabled.go
- pkg/manager-server/server_local.go
- pkg/manager-server/server_mock.go
- pkg/manager-server/server_remote.go
- pkg/manager-server/storage.go
- pkg/tests/filesystem/file_system_test.go
I identified another issue with Lustre where the mount point, although it is stored in the recovery database, it's not loaded into the various implementations of the file system API. This caused an empty mountpoint so nothing was unmounted on delete, which caused the `zpool destroy` to fail with "cannot destroy 'lus-ostpool': pool is busy"
The file system object is really not the place to track the mount point since it is not persistent. It's solely in the file share data, so the API was changed to accept the mountpoint on the `Unmount()` call. The mountpoint was then removed from the FileSystem structure, making the file system "stateless"
I also corrected what I could in the file-share recovery code so the latest applied mountpoint is stored in the database. There's still some recovery …
> Further fixes for File Share recovery

- pkg/api/fabric.go
- pkg/manager-fabric/config.go
- pkg/manager-fabric/config_default.yaml
- pkg/manager-fabric/manager.go
- pkg/manager-nvme/manager.go
- pkg/rfsf/pkg/common/alias.go
This adds the ability to set the PartLocation from the Fabric Manager's config file. Each port defined in the config now supports `slot` and each switch can set a `slotPrefix` for the corresponding `slot`.
These values are stored in the Storage Controller's `PartLocation`.
Signed-off-by: Blake Devcich <blake.devcich@hpe.com>
> Added Slot/PartLocation support to Storage Controller

- tools/create-write-delete-namespaces.sh
- tools/lvm.sh
- tools/nvme.sh
- tools/readme.md
- Add readme.md demonstrating expected tool script usage for namespace manipulation
- Add examples to nvme.sh
- Extend create-write-delete.sh to format the namespace before deleting the namespace to see if delete_ns speeds up.
Add readme.md that demonstrates usage
> Tools directory changes:

- pkg/logging/cli.go
- pkg/manager-server/file_system_api.go
- pkg/manager-server/file_system_gfs2.go
- pkg/manager-server/file_system_lustre.go
- pkg/manager-server/file_system_lvm.go
- pkg/manager-server/file_system_xfs.go
- pkg/var_handler/var_handler.go
- pkg/var_handler/var_handler_test.go
All FS commandlines are passed in from the nnf-sos layer.
Introduce variables into the commandlines, to allow the EC layer to insert dynamic values.
Let the NNF logs see the FS commands and their results.
Signed-off-by: Dean Roehrich <dean.roehrich@hpe.com>
> Allow NnfStorageProfile to pass args for mkfs, lvm, lustre

- pkg/manager-server/file_system_api.go
- pkg/manager-server/file_system_gfs2.go
- pkg/manager-server/file_system_xfs.go
Mount the file system and set the owner/group to the desired values. This is only necessary for XFS and gfs2 file systems.
Signed-off-by: Matt Richerson <matthew.richerson@Matts-MacBook-Pro.local>
> RABSW-1083: Set owner and group after mkfs

- pkg/manager-nvme/manager.go
- pkg/manager-nvme/nvme_api.go
- pkg/manager-nvme/nvme_cli.go
- pkg/manager-nvme/nvme_device.go
- pkg/manager-nvme/nvme_direct_device.go
- pkg/manager-nvme/nvme_mock.go
NVMe Manager was not tracking the unallocated byte count during namespace creation or deletion, instead relying on various GETs of redfish endpoints to call `refreshCapacity()`. This change removes the `refreshCapacity()` method and tracks the unallocated capacity whenever a namespace is created or deleted.
> NVMe Manager: Unallocated Bytes can get out of sync with drive data

- pkg/manager-nnf/allocation_policy.go
- pkg/manager-nnf/manager.go
- pkg/manager-nnf/storage_group.go
- pkg/manager-nnf/storage_pool.go
- pkg/manager-nvme/manager.go
- pkg/persistent/kvstore.go
After all storage pool replays are complete, remove any namespaces that are not associated with the storage pools.
Signed-off-by: Blake Devcich <blake.devcich@hpe.com>
> Storage Pools: Remove abandoned namespaces

- tools/nvme.sh
Add the "detach" subcommand to allow detaching namespaces from each drive for the specified controller.
> Add "detach" subcommand to nvme.sh

- tools/rabbit-s.sh
The '-w' option, to set the delimiter to spaces and tabs, is an extension only available on Darwin.
We only need spaces so revert to the -d option
> Ensure 'rabbit-s.sh enable-logging' works with Linux distros

- pkg/manager-fabric/config_default.yaml
> Final Rabbit hardware does not have slot prefix 'J' on the front panel

- pkg/manager-server/file_system_api.go
When Unmount() is called, the IsMountPoint() check returns (false, ErrNotExist) when the target path doesn't exist. We want to ignore ErrNotExist, but return all other errors
It's still unclear _how_ we got into this state, but this should ensure the File Share delete doesn't get stuck.
> Fix for failed unmount when IsMountPoint() returns ErrNotExist

- pkg/manager-nnf/allocation_policy.go
The spare allocation policy was incorrectly considering drives with 0 bytes to spare. As long as the cumulative spare bytes amongst all drives is available, the policy check would pass and we'd try to allocate 1/16th on all the drives, even drives with 0 bytes to spare. The fix is to only consider storage devices that are both enabled and have spare bytes.
Another bug is present in the un-relaxed allocation mode, where we would only consider allocations that are a multiple of the drive count. This doesn't take into consideration that all drives should present 1/16th of the request capacity to keep things balanced.
> Fix for the spare allocation policy logic

- pkg/manager-nvme/nvme_mock.go
- pkg/manager-nvme/nvme_mock_persistence.go
For mock NVMe devices, I goofed in #43 when using the capacity-in-bytes vs capacity-in-sectors
> NVMe Mock Device has incorrect capacity

- pkg/ec/error.go
- pkg/manager-nnf/manager.go
- Adds a retryable error type to ec errors
- Adds retry delay to ec errors
- Improves error string
- Use the above when creating a file share instead of indefinitely hanging (RABSW-587)
> RABSW-587: Support for retryable errors. Don't hang file share create

- tools/lvm.sh
- tools/nvme.sh
- tools/rabbit-s.sh
- tools/switch.sh
- Add switch.sh tool script
- Add options to bind.sh to bind other compute nodes to virtual functions
[root@RabbitP-CPU2 tools]# ./switch.sh slot-info
Execute slot-info on /dev/switchtec0
DEVICE: /dev/switchtec0 PAX_ID: 1 SLOT: 4	    Physical Port ID 8 (EP attached):
DEVICE: /dev/switchtec0 PAX_ID: 1 SLOT: 5	    Physical Port ID 10 (EP attached):
DEVICE: /dev/switchtec0 PAX_ID: 1 SLOT: 6	    Physical Port ID 12 (EP attached):
DEVICE: /dev/switchtec0 PAX_ID: 1 SLOT: 2	    Physical Port ID 14 (EP attached):
DEVICE: /dev/switchtec0 PAX_ID: 1 SLOT: 1	    Physical Port ID 16 (Not attached)
DEVICE: /dev/switchtec0 PAX_ID: 1 SLOT: 9	    Physical Port ID 18 (EP attached):
DEVICE: /dev/switchtec0 PAX_ID: 1 SLOT: 10	    Physical Port ID 20 (EP attached):
DEVICE: /dev/switchtec0 PAX_ID: 1 SLOT: 11 …
> Tool script improvements

- pkg/manager-server/file_system_lustre.go
If there are multiple of the same Lustre target on a single server, the zpool name collides.
Signed-off-by: Matt Richerson <matthew.richerson@Matts-MacBook-Pro.local>
> RABSW-1081: Add index to zpool name

- pkg/manager-nnf/file_system.go
- pkg/manager-nnf/manager.go
- pkg/manager-nnf/router.go
- pkg/manager-remote/manager.go
- pkg/manager-server/file_system_api.go
- pkg/manager-server/file_system_gfs2.go
- pkg/manager-server/file_system_lustre.go
- pkg/manager-server/file_system_lvm.go
- pkg/manager-server/file_system_test.go
- pkg/manager-server/file_system_xfs.go
- pkg/manager-server/file_system_zfs.go
- pkg/tests/filesystem/file_system_test.go
- Fix the delete share endpoint not registering the delete method
- Throw in some OEM defaults so nnf-ec can run standalone and support file-systems & file-shares. I'm not sure I like this implementation, it is a rather hacky way to get nnf-ec to where it was before the Storage Profile changes.
- Refactor LVM so the volume group is activated first. In my testing, this didn't change anything, but it allows me to use a common activation function, `activateVolumeGroup`, for both existing volumes from vgscan and new volumes.
> Fixes / Improvements for file system handling

- pkg/manager-server/file_system_api.go
- pkg/manager-server/file_system_gfs2.go
- pkg/manager-server/file_system_lustre.go
- pkg/manager-server/file_system_lvm.go
- pkg/manager-server/file_system_zfs.go
- pkg/tests/filesystem/file_system_test.go
I found it useful to have control over the vgchange and (lv|vg)remove options while testing recent changes to nnf-ec. rabbit-htx is currently not running lvmlockd since I am rebuilding the pacemaker cluster for the NNF fencing changes, so providing the `--nolocking` argument has proven quite useful. However, this could only be done on setup, hence I am adding (lv|vg)remove options for TOTAL CONTROL
Dean suggested I also add vgchange while I am at it, so I did. But vgchange only applies when activating, `--activate (y|n)`. I didn't apply the arguments to `vgchange --lock-start` because I thought that one should never be configurable. But if you think it's useful I could add it to the GFS2 options.
After merge, this will need coordination with nnf-sos and the default storage profile. …
> LVM Command Arguments for vgchange, vgremove, and lvremove

- scripts/allocate-compute.py
```
usage: allocate-compute.py [-h] [--node {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} [{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} ...]] [--size SIZE] [--host HOST] [--port PORT]
Allocate storage and assign it to a compute node(s)
optional arguments:
-h, --help            show this help message and exit
--node {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} [{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} ...]
the node index to attach to
--size SIZE           storage pool size (default 500GB)
--host HOST           specify a server endpoint
--port PORT           specify a server port
Must executed on Rabbit with nnf-ec running
```
> Simple script to allocate & assign storage for compute nodes

- pkg/manager-server/file_system_api.go
- pkg/manager-server/file_system_lvm.go
- pkg/manager-server/file_system_raw.go
- Mounts weren't working for Raw allocations because they were creating a directory instead of a file to mount
- User and group are set on the device bind mount so user containers can access them
Signed-off-by: Matt Richerson <matthew.richerson@hpe.com>
> RABSW-1097: Bind mount LVM devices and set permissions

- tools/_util.sh
- tools/nvme.sh
- tools/switch.sh
Looks like this:
[root@rabbit-node-1 tools]# ./switch.sh ep-tunnel-status
Execute switch ep-tunnel status on /dev/switchtec0
0x1300	Status: Enabled
0x1500	Status: Enabled
0x1a00	Status: Enabled
0x1900	Status: Enabled
0x1600	Status: Enabled
0x1400	Status: Enabled
0x1800	Status: Enabled
0x1700	Status: Enabled
Execute switch ep-tunnel status on /dev/switchtec1
0x3b00	Status: Enabled
0x3c00	Status: Enabled
0x3d00	Status: Enabled
0x3e00	Status: Enabled
0x3f00	Status: Enabled
0x4000	Status: Enabled
0x4200	Status: Enabled
0x4100	Status: Enabled
[root@RabbitP-CPU2 tools]# ./switch.sh ep-tunnel-enable
Execute switch ep-tunnel enable on /dev/switchtec0
Execute switch ep-tunnel enable on /dev/switchtec1
> Add ep-tunnel commands for switch.sh

- internal/switchtec/cmd/nvme/primary_ctrl_caps.go
- internal/switchtec/main.go
- internal/switchtec/pkg/nvme/nvme.go
Looks like this
```bash
Identify Primary Controller:
CNTLID: Controller Identifier                      : 0x81
PORTID: Port Identifier                            : 0x0
CRT   : Controller Resource Type                   : 0x3
VQFRT : VQ Resources Flexible Total                : 192
VQRFA : VQ Resources Flexible Assigned             : 1
VQRFAP: VQ Resources Flexible Allocated to Primary : 0
VQPRT : VQ Resources Private Total                 : 128
VQFRSM: VQ Resources Flexible Secondary Maximum    : 8
VQGRAN: VQ Flexible Resource Preferred Granularity : 1
VIFRT : VI Resources Flexible Total                : 192
VIRFA : VI Resources Flexible Assigned             : 1
VIRFAP: VI Resources Flexible Allocated to Primary : 0
VIPRT : VI Resources Private Total                 : 128
VIFRSM: VI …
```
> NVMe Identify Primary Controller Capabilities

- pkg/manager-nnf/manager.go
- pkg/manager-server/server_local.go
- pkg/manager-server/storage.go
Optimize NVMe discovery on the rabbit (server_local)...
1. Any discover() call refreshes _all_ storage resources, not just the one of interest. This will help in scenarios where many storages are requested at once.
2. Convert from using a series of commands (`ls`, `nvme id-ns`, `nvme id-ns --namespace-id=`) to using one giant `nvme list` command.
Also, I was using the NS <ID, GUID> as the matching criteria. While a GUID collision is next to impossible, switching to use <ID, _SerialNumber_> pair is **more** correct (FWIW).
In my workflow test, running 5 XFS workflows with 2 allocations each, Setup is achieved in ~50s. Previously this took ~100s.
> Optimize NVMe Discovery on the Rabbit

- pkg/manager-server/file_system_api.go
Commands can sometimes hang forever without returning an error. Add a timeout whenever running commands. The
timeout is adjustable through the NNF_EC_COMMAND_TIMEOUT_SECONDS environment variable.`
Signed-off-by: Matt Richerson <matthew.richerson@hpe.com>
> RABSW-1158: Add timeout to commands run by nnf-ec

- pkg/manager-nnf/manager.go
If the mount of a fileshare failed, then the whole fileshare needs to be torn down since none of the partial setup information is saved.
> Github-32: Clean up fileshare create after mount failure

- pkg/manager-server/file_system_api.go
- pkg/manager-server/file_system_lustre.go
Additionally, catch timeouts and include an error message to indicate timeout.
Tested by:
- Stubbing out zpool destroy with a sleep to hit the timeout
- In PostRun, exec into the node manager pod to unmount and destroy the zpool. Ensure Teardown completes successfully.
> For zfs backed lustre, skip zpool destroy if zpool list fails

- internal/switchtec/pkg/nvme/nvme.go
- pkg/manager-nvme/manager.go
- tools/rabbit-s.sh
Retry `identify common namespace` during initialization to recover from intermittent failures seen during power cycle testing.
> Retry CommonNamespaceIdentifier

- pkg/manager-nvme/manager.go
Avoid doing a divide-by-zero and panicing the process.
> Handle empty capacity when a drive cannot be found.

- pkg/manager-fabric/manager.go
In the case where we cannot open a /dev/switchtecX device, give a useful panic message rather than just dereferencing a nil pointer.
Earlier in the log there will be an error stating "Error opening path", and another stating "Failed to identify switch". The nil deference was happening much later, so it was not obviously connected to those.
See https://github.com/NearNodeFlash/NearNodeFlash.github.io/issues/178 for more details.
> Identify inability to open a switch, avoid nil dereference

- tools/collectNVLogs.sh
- tools/rabbit-s.sh
- tools/show-drive-ports.sh
- tools/switch.sh
- tools/timestamp-log.sh
tools/ script modifications and additions:
`collectNVLog.sh` - add the switchtec RAM log to the logs collected.
`rabbit-s.sh` - add log setting for issues we've seen in the switches
`show-drive-ports.sh` - test script to check drive PCI link speeds and widths as seen from Rabbit
`switch.sh` - Add verbose (-v) option to specify the x-name of the compute and rabbit nodes along with the temperature of the PAXs
> tools script additions and improvements

- scripts/admin-node-scripts/updateDriveFirmwareMfg.sh
This script is used in manufacturing to update NVMe drive firmware and log the result.
> Add the drive firmware update script used in manufacturing

- internal/switchtec/pkg/switchtec/events.go
- pkg/manager-fabric/manager.go
- pkg/manager-fabric/monitor.go
- pkg/manager-nnf/aer.go
- pkg/manager-nnf/allocation_policy.go
- pkg/manager-nnf/api.go
- pkg/manager-nnf/manager.go
- pkg/manager-nnf/servicer.go
- pkg/manager-nvme/manager.go
- pkg/manager-remote/manager.go
- scripts/admin-node-scripts/updateDriveFirmwareMfg.sh
- tools/collectNVLogs.sh
- tools/rabbit-s.sh
- tools/show-drive-ports.sh
- tools/switch.sh
- tools/timestamp-log.sh
> Release v0.1.1

- Dockerfile
- pkg/controller.go
- pkg/ec/ec.go
- pkg/manager-nnf/allocation_policy.go
- pkg/manager-nnf/manager.go
- pkg/manager-nnf/storage_pool.go
- pkg/manager-nvme/manager.go
- pkg/tests/benchmarks/benchmark_test.go
- pkg/tests/filesystem/file_system_test.go
- pkg/tests/nnf_test.go
- pkg/tests/recovery/recovery_test.go
- Add the `deleteUnknownVolumes` command line parameter, default is false to avoid accidentally removing volumes when starting nnf-ec as a command
- Starting the HTTP server is no longer the default. You must specify `-http` now for that behavior.
Examples:
```bash
./nnf-ec
```
- Initializes all PCI related items (PAXs and NVMe drives)
- Leaves unknown NVMe namespaces alone
- Exits after initialization
```bash
./nnf-ec -http -deleteUnknownVolumes
```
- Provides the old default behavior where all unknown volumes are deleted after initialization and the HTTP server is started to accept redfish commands
> New default cli settings

- pkg/manager-nnf/manager.go
- pkg/manager-nvme/manager.go
A storage pool delete failure can result in double deleting of the NVMe namespaces. Return success even if some of the namespaces were not removed. We'll leak these namespaces for now.
> Return success on delete storage pool failure

- pkg/manager-nnf/allocation_policy.go
- pkg/manager-nnf/manager.go
- pkg/manager-nvme/manager.go
- scripts/interactive.py
- tools/switch.sh
- implement the `strict` allocation policy that guarantees that the capacity consumed from each drive in a storage pool is the same. This may consume more space, but the uniformity is beneficial to all users of the space.
- when namespaces that have not been assigned to a storage pool are discovered and the `deleteUnknownVolumes` command line parameter is specifed, those namespaces are deleted. This PR includes a fix that correctly returns the space to the storage devices for unknown namespaces. The result of this bug was that nnf-ec incorrectly reported out-of-space conditions when the available space on the drive was present after purging unknown namespaces.
We need a change in `nnf-sos` to request the `strict` allocation compliance which will be coming after this is merged to master.
> Uniform namespaces

- internal/switchtec/cmd/config/config.go
- pkg/manager-fabric/manager.go
- pkg/manager-nnf/manager.go
- pkg/manager-nnf/storage_group.go
- pkg/manager-nnf/storage_pool.go
- tools/nnf-switch.sh
Allow storage groups to be created/deleted when the compute node is not connected. This eases startup for ansible-created filesystems where the compute node is powered off.
This change also has the effect of repairing a segfault that happens when nnf-ec restarts after a compute node has been powered off. nnf-ec searches for the storage group, but because the endpoint is down is not accessible. When a delete operation on storage groups for that compute node result in segfaults.
> nnf-ec segfault during storage group delete

- pkg/manager-nnf/manager.go
- pkg/manager-nnf/storage_pool.go
- tools/nnf-nvme.sh
- tools/nnf-switch.sh
Log errors and continue on the initialization and delete paths for storage groups/pools
To test these paths, I used nnf-ec standalone on the texas system and performed various deletion operations with missing namespaces.
> Ignore delete path errors

- pkg/controller.go
- pkg/manager-nnf/manager.go
- pkg/manager-nnf/storage_group.go
- pkg/manager-nnf/storage_pool.go
- pkg/manager-nvme/manager.go
- pkg/tests/benchmarks/benchmark_test.go
- pkg/tests/filesystem/file_system_test.go
- pkg/tests/nnf_test.go
- pkg/tests/recovery/recovery_test.go
- scripts/interactive.py
- tools/zpool.sh
This PR introduces a command line parameter to control automatic storage pool volume recovery.
**Automatic Volume Replacement**
- Added a new CLI flag `--replaceMissingVolumes` to enable automatic replacement of missing volumes in storage pools
- Implemented logic to detect and replace missing volumes during system initialization or when storage pools are patched
- Modified storage service initialization to support the new functionality
**New Utility**
- Added `zpool.sh` script for creating and managing ZFS pools on Rabbit systems
> Patch commandline parameter

- pkg/manager-nnf/manager.go
- pkg/persistent/storage_api.go
- pkg/persistent/storage_json.go
- pkg/persistent/storage_local.go
Periodic garbage collection is required to keep the database in good shape. This commit adds the necessary apparatus to garbage collect the nnf-ec database once per day.
Fixes https://github.com/NearNodeFlash/NearNodeFlash.github.io/issues/281
> Add periodic garbage collector for key-value store

- Makefile
- pkg/manager-nvme/manager.go
- device communication errors
- timeout errors
- device not found errors
Take the following actions:
- record the state of the storage (NVMe device) as offline
- publish event to trigger nnf-sos to query the storage state
Resolves https://github.com/NearNodeFlash/NearNodeFlash.github.io/issues/275
> During NVMe operations, when system-level errors occur such as:
